/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as SunshineRouteImport } from './routes/sunshine'
import { Route as SolicitudRouteImport } from './routes/solicitud'
import { Route as PulpinaRouteImport } from './routes/pulpina'
import { Route as PoliticasRouteImport } from './routes/politicas'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as MoonRouteImport } from './routes/moon'
import { Route as MenRouteImport } from './routes/men'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AccesoAdminRouteImport } from './routes/acceso-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as ColeccionSlugRouteImport } from './routes/coleccion.$slug'
import { Route as AdminStockRouteImport } from './routes/admin/stock'
import { Route as AdminProductosRouteImport } from './routes/admin/productos'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminDescuentosRouteImport } from './routes/admin/descuentos'
import { Route as AdminConfiguracionRouteImport } from './routes/admin/configuracion'
import { Route as AdminColeccionesRouteImport } from './routes/admin/colecciones'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const SunshineRoute = SunshineRouteImport.update({
  id: '/sunshine',
  path: '/sunshine',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudRoute = SolicitudRouteImport.update({
  id: '/solicitud',
  path: '/solicitud',
  getParentRoute: () => rootRouteImport,
} as any)
const PulpinaRoute = PulpinaRouteImport.update({
  id: '/pulpina',
  path: '/pulpina',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasRoute = PoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const MoonRoute = MoonRouteImport.update({
  id: '/moon',
  path: '/moon',
  getParentRoute: () => rootRouteImport,
} as any)
const MenRoute = MenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoAdminRoute = AccesoAdminRouteImport.update({
  id: '/acceso-admin',
  path: '/acceso-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionSlugRoute = ColeccionSlugRouteImport.update({
  id: '/coleccion/$slug',
  path: '/coleccion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/admin/stock',
  path: '/admin/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/admin/productos',
  path: '/admin/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDescuentosRoute = AdminDescuentosRouteImport.update({
  id: '/admin/descuentos',
  path: '/admin/descuentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/admin/configuracion',
  path: '/admin/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminColeccionesRoute = AdminColeccionesRouteImport.update({
  id: '/admin/colecciones',
  path: '/admin/colecciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso-admin': typeof AccesoAdminRoute
  '/carrito': typeof CarritoRoute
  '/contacto': typeof ContactoRoute
  '/men': typeof MenRoute
  '/moon': typeof MoonRoute
  '/nosotros': typeof NosotrosRoute
  '/politicas': typeof PoliticasRoute
  '/pulpina': typeof PulpinaRoute
  '/solicitud': typeof SolicitudRoute
  '/sunshine': typeof SunshineRoute
  '/tienda': typeof TiendaRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/colecciones': typeof AdminColeccionesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/descuentos': typeof AdminDescuentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/stock': typeof AdminStockRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso-admin': typeof AccesoAdminRoute
  '/carrito': typeof CarritoRoute
  '/contacto': typeof ContactoRoute
  '/men': typeof MenRoute
  '/moon': typeof MoonRoute
  '/nosotros': typeof NosotrosRoute
  '/politicas': typeof PoliticasRoute
  '/pulpina': typeof PulpinaRoute
  '/solicitud': typeof SolicitudRoute
  '/sunshine': typeof SunshineRoute
  '/tienda': typeof TiendaRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/colecciones': typeof AdminColeccionesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/descuentos': typeof AdminDescuentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/stock': typeof AdminStockRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso-admin': typeof AccesoAdminRoute
  '/carrito': typeof CarritoRoute
  '/contacto': typeof ContactoRoute
  '/men': typeof MenRoute
  '/moon': typeof MoonRoute
  '/nosotros': typeof NosotrosRoute
  '/politicas': typeof PoliticasRoute
  '/pulpina': typeof PulpinaRoute
  '/solicitud': typeof SolicitudRoute
  '/sunshine': typeof SunshineRoute
  '/tienda': typeof TiendaRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/colecciones': typeof AdminColeccionesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/descuentos': typeof AdminDescuentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/stock': typeof AdminStockRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso-admin'
    | '/carrito'
    | '/contacto'
    | '/men'
    | '/moon'
    | '/nosotros'
    | '/politicas'
    | '/pulpina'
    | '/solicitud'
    | '/sunshine'
    | '/tienda'
    | '/admin/categorias'
    | '/admin/colecciones'
    | '/admin/configuracion'
    | '/admin/descuentos'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/stock'
    | '/coleccion/$slug'
    | '/producto/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso-admin'
    | '/carrito'
    | '/contacto'
    | '/men'
    | '/moon'
    | '/nosotros'
    | '/politicas'
    | '/pulpina'
    | '/solicitud'
    | '/sunshine'
    | '/tienda'
    | '/admin/categorias'
    | '/admin/colecciones'
    | '/admin/configuracion'
    | '/admin/descuentos'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/stock'
    | '/coleccion/$slug'
    | '/producto/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/acceso-admin'
    | '/carrito'
    | '/contacto'
    | '/men'
    | '/moon'
    | '/nosotros'
    | '/politicas'
    | '/pulpina'
    | '/solicitud'
    | '/sunshine'
    | '/tienda'
    | '/admin/categorias'
    | '/admin/colecciones'
    | '/admin/configuracion'
    | '/admin/descuentos'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/stock'
    | '/coleccion/$slug'
    | '/producto/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoAdminRoute: typeof AccesoAdminRoute
  CarritoRoute: typeof CarritoRoute
  ContactoRoute: typeof ContactoRoute
  MenRoute: typeof MenRoute
  MoonRoute: typeof MoonRoute
  NosotrosRoute: typeof NosotrosRoute
  PoliticasRoute: typeof PoliticasRoute
  PulpinaRoute: typeof PulpinaRoute
  SolicitudRoute: typeof SolicitudRoute
  SunshineRoute: typeof SunshineRoute
  TiendaRoute: typeof TiendaRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminColeccionesRoute: typeof AdminColeccionesRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminDescuentosRoute: typeof AdminDescuentosRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminStockRoute: typeof AdminStockRoute
  ColeccionSlugRoute: typeof ColeccionSlugRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunshine': {
      id: '/sunshine'
      path: '/sunshine'
      fullPath: '/sunshine'
      preLoaderRoute: typeof SunshineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitud': {
      id: '/solicitud'
      path: '/solicitud'
      fullPath: '/solicitud'
      preLoaderRoute: typeof SolicitudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulpina': {
      id: '/pulpina'
      path: '/pulpina'
      fullPath: '/pulpina'
      preLoaderRoute: typeof PulpinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas': {
      id: '/politicas'
      path: '/politicas'
      fullPath: '/politicas'
      preLoaderRoute: typeof PoliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moon': {
      id: '/moon'
      path: '/moon'
      fullPath: '/moon'
      preLoaderRoute: typeof MoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men': {
      id: '/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso-admin': {
      id: '/acceso-admin'
      path: '/acceso-admin'
      fullPath: '/acceso-admin'
      preLoaderRoute: typeof AccesoAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccion/$slug': {
      id: '/coleccion/$slug'
      path: '/coleccion/$slug'
      fullPath: '/coleccion/$slug'
      preLoaderRoute: typeof ColeccionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/admin/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/admin/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/descuentos': {
      id: '/admin/descuentos'
      path: '/admin/descuentos'
      fullPath: '/admin/descuentos'
      preLoaderRoute: typeof AdminDescuentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/colecciones': {
      id: '/admin/colecciones'
      path: '/admin/colecciones'
      fullPath: '/admin/colecciones'
      preLoaderRoute: typeof AdminColeccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoAdminRoute: AccesoAdminRoute,
  CarritoRoute: CarritoRoute,
  ContactoRoute: ContactoRoute,
  MenRoute: MenRoute,
  MoonRoute: MoonRoute,
  NosotrosRoute: NosotrosRoute,
  PoliticasRoute: PoliticasRoute,
  PulpinaRoute: PulpinaRoute,
  SolicitudRoute: SolicitudRoute,
  SunshineRoute: SunshineRoute,
  TiendaRoute: TiendaRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminColeccionesRoute: AdminColeccionesRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminDescuentosRoute: AdminDescuentosRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminStockRoute: AdminStockRoute,
  ColeccionSlugRoute: ColeccionSlugRoute,
  ProductoSlugRoute: ProductoSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
